### ISSUE TITLE
figure out versioning

### ISSUE THREAD

**Issue by secureshellprotocol** [ECE-366-Final-Project/Back-End#24]
We probably should use tags to manage versions, since we've done rapid development but have not incremented the version.
Could @Vaibhav-Hariani or @LaniW investigate an optimal way to handle versioning? ideally its handled by git and increments by commit. We'd also have to think about how maven handles versioning, since it defines a version tag.
We also should agree on a schema. I vote for [semantic versioning](https://en.wikipedia.org/wiki/Software_versioning#Semantic_versioning)

Worst case we are just conscious of the work we do, and increment versioning manually.

**Comment by secureshellprotocol** [comment]
https://stackoverflow.com/questions/37814286/how-to-manage-the-version-number-in-git
https://stackoverflow.com/questions/5195859/how-do-you-push-a-tag-to-a-remote-repository-using-git

just some info on `git tag` and `git describe` which could be helpful

**Comment by LaniW** [comment]
@secureshellprotocol @Vaibhav-Hariani 

I did some research and it looks like we might be able to implement [Git Hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) which are scripts that run automatically when anything happens in a repository. It also looks like it is typically written in _Bash_ which I am not as well versed with beyond what we have done in ECE160. 

The following is similar to what I saw online and it might be a good starting point for versioning?

```
#!/bin/bash

VERSION_FILE="VERSION"

# Read the current version
CURRENT_VERSION=$(cat $VERSION_FILE)

# Parse the major, minor, and patch numbers
MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)

# Increment the version based on the Git commit message
case "$1" in
  "fix")
    PATCH=$((PATCH + 1))
    ;;
  "feat")
    MINOR=$((MINOR + 1))
    PATCH=0
    ;;
  "breaking")
    MAJOR=$((MAJOR + 1))
    MINOR=0
    PATCH=0
    ;;
  *)
    echo "Invalid commit type."
    exit 1
    ;;
esac

# Update the version file
NEW_VERSION="$MAJOR.$MINOR.$PATCH"
echo $NEW_VERSION > $VERSION_FILE

# Output the updated version
echo "Version updated to $NEW_VERSION"
```
